CrudCarreras/Controllers/CarrerasController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CrudCarreras.Data;
using CrudCarreras.Models;
using Microsoft.AspNetCore.Http;

namespace CrudCarreras.Controllers
{
    public class CarrerasController : Controller
    {
        private readonly CrudCarrerasContext _context;

        public CarrerasController(CrudCarrerasContext context)
        {
            _context = context;
        }

        // GET: Carreras
        public async Task<IActionResult> Index()
        {
            var crudCarrerasContext = _context.Carreras.Include(c => c.Participantes);
            return View(await crudCarrerasContext.ToListAsync());
        }

        // GET: Carreras/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carreraModel = await _context.Carreras
                .Include(c => c.Participantes)
                .ThenInclude(p => p.Dorsal)
                .FirstOrDefaultAsync(m => m.CarreraId == id);
            if (carreraModel == null)
            {
                return NotFound();
            }

            return View(carreraModel);
        }

        // GET: Carreras/Create
        public IActionResult Create()
        {
            return View();
        }
        
        

        // POST: Carreras/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CarreraId,Distancia,Descripcion,Fecha")] CarreraModel carreraModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(carreraModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(carreraModel);
        }

        // GET: Carreras/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carreraModel = await _context.Carreras.FindAsync(id);
            if (carreraModel == null)
            {
                return NotFound();
            }
            return View(carreraModel);
        }

        // POST: Carreras/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CarreraId,Distancia,Descripcion,Fecha")] CarreraModel carreraModel)
        {
            if (id != carreraModel.CarreraId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(carreraModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarreraModelExists(carreraModel.CarreraId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(carreraModel);
        }

        // GET: Carreras/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carreraModel = await _context.Carreras
                .FirstOrDefaultAsync(m => m.CarreraId == id);
            if (carreraModel == null)
            {
                return NotFound();
            }

            return View(carreraModel);
        }

        // POST: Carreras/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var carreraModel = await _context.Carreras.FindAsync(id);
            _context.Carreras.Remove(carreraModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CarreraModelExists(int id)
        {
            return _context.Carreras.Any(e => e.CarreraId == id);
        }

        // POST: Carreras/UploadCodigos/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UploadCodigos(int? id, IFormFile codigosFile)
        {
            
            if (id == null)
            {
                return NotFound();
            }
            
            var carreraModel = _context.Carreras
                .Include(c => c.Dorsales)
                .First(c => c.CarreraId == id);
            if (carreraModel == null)
            {
                return NotFound();
            }
            
            
            if (codigosFile.Length > 0)
            {
                
                var result = new StringBuilder();
                using (var reader = new StreamReader(codigosFile.OpenReadStream()))
                {
                    while (reader.Peek() >= 0)
                        result.AppendLine(await reader.ReadLineAsync()); 
                }
                
                Regex regex = new Regex(@"^([a-fA-F\d]{16}) {4}(0*\d{1,"+carreraModel.Dorsales.Count.ToString().Length+"})$", RegexOptions.Multiline);
                MatchCollection matchCollection = regex.Matches(result.ToString());
                foreach (Match m in matchCollection)
                {
                    GroupCollection g = m.Groups;
                    string codigo = g[1].Value;
                    try
                    {
                        int dorsal = Int32.Parse(g[2].Value);
                        
                        DorsalModel dorsalModel = _context.Dorsales
                            .FirstOrDefault(d => d.Numero == dorsal);

                        if (dorsalModel == null)
                        {
                            Console.WriteLine("No existe participante asociado a la siguiente linea: " + g[0].Value);
                        }
                        else
                        {
                            dorsalModel.Codigo = codigo;
                            _context.Update(dorsalModel);
                            _context.SaveChanges();
                        }
                        
                       
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine("Invalid dorsal number for code: " + codigo);
                        throw;
                    }
                }
             
            }
            
            return RedirectToAction(nameof(Details),new {id=id})
                .WithInfo("Actualización finalizada", "Los dorsales han sido asignados");
        }
        
        // POST: Carreras/UploadTiempos/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UploadTiempos(int? id, IFormFile tiemposFile)
        {
            
            if (id == null)
            {
                return NotFound();
            }
            
            var carreraModel = _context.Carreras
                .Include(c => c.Dorsales)
                .First(c => c.CarreraId == id);
            if (carreraModel == null)
            {
                return NotFound();
            }
            
            
            if (tiemposFile.Length > 0)
            {
                
                var result = new StringBuilder();
                using (var reader = new StreamReader(tiemposFile.OpenReadStream()))
                {
                    while (reader.Peek() >= 0)
                        result.AppendLine(await reader.ReadLineAsync()); 
                }
                
                Regex regex = new Regex(@"^([a-fA-F\d]{16}) {4}(\d{8})$", RegexOptions.Multiline);
                IOrderedEnumerable<Match> matchCollection = regex.Matches(result.ToString()).OrderBy(m => m.Groups[2].Value);
                int posicion = 1;
                foreach (Match m in matchCollection)
                {
                    GroupCollection g = m.Groups;
                    string codigo = g[1].Value;
                    
                    try
                    {
                        DateTime horaLlegada = DateTime.ParseExact(g[2].Value ,"HHmmssff", CultureInfo.InvariantCulture);
                        
                        var horaInicio = carreraModel.Fecha;
                        TimeSpan tiempo = new TimeSpan(0,
                            horaLlegada.Hour - horaInicio.Hour,
                            horaLlegada.Minute - horaInicio.Minute,
                            horaLlegada.Second - horaInicio.Second,
                            horaLlegada.Millisecond  - horaInicio.Millisecond);
                        
                        ParticipanteModel participanteModel = _context.Participantes
                            .Include(p => p.Dorsal)
                            .FirstOrDefault(p => p.Dorsal.Codigo == codigo);
                        

                        if (participanteModel == null)
                        {
                            Console.WriteLine("No existe participante asociado a la siguiente linea: " + g[0].Value);
                        }

CrudCarreras/Controllers/ParticipantesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CrudCarreras.Data;
using CrudCarreras.Models;

namespace CrudCarreras.Controllers
{
    public class ParticipantesController : Controller
    {
        private readonly CrudCarrerasContext _context;

        public ParticipantesController(CrudCarrerasContext context)
        {
            _context = context;
        }

        // GET: Participantes
        public async Task<IActionResult> Index()
        {
            var crudCarrerasContext = _context.Participantes
                .Include(p => p.Carrera)
                .Include(p => p.Dorsal);
            
            return View(await crudCarrerasContext.ToListAsync());
        }

        // GET: Participantes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participanteModel = await _context.Participantes
                .Include(p => p.Carrera)
                .Include(p => p.Dorsal)
                .FirstOrDefaultAsync(m => m.ParticipanteId == id);
            if (participanteModel == null)
            {
                return NotFound();
            }

            return View(participanteModel);
        }

        // GET: Participantes/Create
        public IActionResult Create()
        {
            ViewData["CarreraId"] = new SelectList(_context.Carreras, "CarreraId", "Descripcion");
            return View();
        }

        // POST: Participantes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ParticipanteId,Nombre,Apellidos,DNI,Club,CarreraId")] ParticipanteModel participanteModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(participanteModel);
                _context.SaveChanges();
                

                ICollection<DorsalModel> dorsalesCarrera = _context.Carreras
                    .Include(c => c.Dorsales)
                    .First(c => c.CarreraId == participanteModel.CarreraId).Dorsales;
                int lastDorsalNumber = dorsalesCarrera.Count == 0 ? 0 : dorsalesCarrera.OrderBy(d => d.Numero).Last().Numero;
                DorsalModel nextDorsal = new DorsalModel();
                nextDorsal.Numero = lastDorsalNumber + 1;
                nextDorsal.CarreraId = participanteModel.CarreraId;
                nextDorsal.ParticipanteId = participanteModel.ParticipanteId;
                _context.Add(nextDorsal);
                _context.SaveChanges();
                
                participanteModel.DorsalId = nextDorsal.DorsalId;
                _context.Update(participanteModel);
                
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CarreraId"] = new SelectList(_context.Carreras, "CarreraId", "Descripcion", participanteModel.CarreraId);
            return View(participanteModel);
        }

        // GET: Participantes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participanteModel = await _context.Participantes
                .Include(p => p.Dorsal)
                .FirstOrDefaultAsync(p => p.ParticipanteId == id);
            if (participanteModel == null)
            {
                return NotFound();
            }
            ViewData["CarreraId"] = new SelectList(_context.Carreras, "CarreraId", "Descripcion", participanteModel.CarreraId);
            return View(participanteModel);
        }

        // POST: Participantes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ParticipanteId,Nombre,Apellidos,DNI,Club")] ParticipanteModel participanteModel)
        {
            if (id != participanteModel.ParticipanteId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Participantes.Attach(participanteModel);
                    _context.Entry(participanteModel).Property(p => p.Nombre).IsModified = true;
                    _context.Entry(participanteModel).Property(p => p.Apellidos).IsModified = true;
                    _context.Entry(participanteModel).Property(p => p.DNI).IsModified = true;
                    _context.Entry(participanteModel).Property(p => p.Club).IsModified = true;
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ParticipanteModelExists(participanteModel.ParticipanteId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CarreraId"] = new SelectList(_context.Carreras, "CarreraId", "Descripcion", participanteModel.CarreraId);
            return View(participanteModel);
        }

        // GET: Participantes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participanteModel = await _context.Participantes
                .Include(p => p.Carrera)
                .Include(p => p.Dorsal)
                .FirstOrDefaultAsync(m => m.ParticipanteId == id);
            if (participanteModel == null)
            {
                return NotFound();
            }

            return View(participanteModel);
        }

        // POST: Participantes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var participanteModel = await _context.Participantes.FindAsync(id);
            _context.Participantes.Remove(participanteModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ParticipanteModelExists(int id)
        {
            return _context.Participantes.Any(e => e.ParticipanteId == id);
        }
    }
}

CrudCarreras/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CrudCarreras</title>

    <environment include="Development">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
        <link rel="stylesheet" href="~/lib/tempusdominus-bootstrap/tempusdominus-bootstrap-4.min.css"/>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CrudCarreras</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Carreras" asp-action="Index">Carreras</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Participantes" asp-action="Index">Participantes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @Html.Partial("_StatusMessages")
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - CrudCarreras - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/lib/moment/moment-with-locales.js"></script>
        <script src="~/lib/tempusdominus-bootstrap/tempusdominus-bootstrap-4.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

CrudCarreras/Views/Shared/_StatusMessages.cshtml
@{
    var type = (string)TempData["_alert.type"];
    var title = (string)TempData["_alert.title"];
    var body = (string)TempData["_alert.body"];
}
@if (!string.IsNullOrEmpty(type))
{
    <div class="alert alert-@type alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>@title</strong> @body
    </div>    
}